lvim.builtin.which_key.mappings["a"] = {
	name = "Ass",
	v = { "<cmd>AssShow<CR>", "Video" },
	s = { "<cmd>AssPlay line<CR>", "Audio line" },
	t = { "<cmd>AssPlay all<CR>", "Audio all" },
	e = { "<cmd>AssPlayBG begin<CR>", "Audio BG start" },
	d = { "<cmd>AssPlayBG end<CR>", "Audio BG end" },
	q = { "<cmd>AssPlayBG before<CR>", "Audio BG before" },
	w = { "<cmd>AssPlayBG after<CR>", "Audio BG after" },
	x = { "<cmd>AssSplitLine<CR>", "Split Line" },
	c = { "<cmd>AssReplace<CR>0fN<cmd>AssSplitUp<CR>", "Only copy the line." },
	z = { "<cmd>lua require'ass'.opts.line_hook = require'PhosCity.assfilters'.filter1<CR>", "Apply Filter 1" },
	b = { "<cmd>lua require'ass'.opts.line_hook = require'PhosCity.assfilters'.filter2<CR>", "Apply Filter 2" },
	n = { ":AssSplit<Space>", "Split File", silent = false },
}
